/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import connexion.Connexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author AMINE
 */
public class Barchart extends javax.swing.JInternalFrame {
    private DefaultCategoryDataset dataset;
    private Connexion connexion;
    /**
     * Creates new form Barchart
     */
    public Barchart() {
        initComponents();
        connexion = Connexion.getInstance();
        this.setTitle("Répartition des stages par entreprise");
        
        dataset = new DefaultCategoryDataset();
        load();
        JFreeChart barChart = ChartFactory.createBarChart(
                "Répartition des stages",
                "Entreprise",
                "Nombre de sujets",
                dataset
        );
        
ChartPanel chartPanel = new ChartPanel(barChart);
        setContentPane(chartPanel);
    }
    
    private void load() {
        String req = "SELECT entreprise, COUNT(*) AS nb_stages FROM stage GROUP BY entreprise";
        
        try (PreparedStatement ps = connexion.getCn().prepareStatement(req);
                ResultSet rs = ps.executeQuery()) {

            dataset.clear();  // Efface les anciennes données

            while (rs.next()) {
                String entreprise = rs.getString("entreprise");
                int nbStages = rs.getInt("nb_stages");
                dataset.addValue(nbStages, "Stages", entreprise);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur de connexion à la base de données !");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
