/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JInternalFrame;

/**
 *
 * @author FATI
 */
public class MDIApplication extends javax.swing.JFrame {

    // Instance statique unique
    private static MDIApplication instance;

    // Constructeur privé pour empêcher l'instanciation directe
    private MDIApplication() {
        initComponents();
        this.setTitle("Gestion des Projets de Recherche");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    // Méthode pour obtenir l'instance unique
    public static MDIApplication getInstance() {
        if (instance == null) {
            instance = new MDIApplication();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        projetRechercheMenuItem = new javax.swing.JMenuItem();
        enseignantMenuItem = new javax.swing.JMenuItem();
        affectationProjetMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setPreferredSize(new java.awt.Dimension(800, 600));
        desktopPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        projetRechercheMenuItem.setMnemonic('o');
        projetRechercheMenuItem.setText("ProjetRecherche");
        projetRechercheMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projetRechercheMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(projetRechercheMenuItem);

        enseignantMenuItem.setText("Enseignant");
        enseignantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enseignantMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(enseignantMenuItem);

        affectationProjetMenuItem.setText("AffectationProjet");
        affectationProjetMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affectationProjetMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(affectationProjetMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Fonctionnalités");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("FiltrageDesProjetsByAxe");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("RechercherProjetByTitre");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Statiques");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Nombre des projets par axe");
        helpMenu.add(contentMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed


    private void projetRechercheMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projetRechercheMenuItemActionPerformed
        ProjetRechercheForm prf = ProjetRechercheForm.getInstance();
        if (!prf.isVisible()) {
            desktopPane.add(prf);
            prf.setVisible(true);
            prf.toFront();
        }
    }//GEN-LAST:event_projetRechercheMenuItemActionPerformed

    private void affectationProjetMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affectationProjetMenuItemActionPerformed
        // TODO add your handling code here:
        AffectationProjetForm apf = AffectationProjetForm.getInstance();
        if (!apf.isVisible()) {
            desktopPane.add(apf);
            apf.setVisible(true);
            apf.toFront();
        }
    }//GEN-LAST:event_affectationProjetMenuItemActionPerformed

    private void enseignantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enseignantMenuItemActionPerformed
        // TODO add your handling code here:
        EnseignantForm ef = EnseignantForm.getInstance();
        if (!ef.isVisible()) {
            desktopPane.add(ef);
            ef.setVisible(true);
            ef.toFront();
        }
    }//GEN-LAST:event_enseignantMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        ProjetByAxeForm prs = ProjetByAxeForm.getInstance();
        if (!prs.isVisible()) {
            desktopPane.add(prs);
            prs.setVisible(true);
            prs.toFront();
        }
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        ProjetByTitreForm prs = ProjetByTitreForm.getInstance();
        if (!prs.isVisible()) {
            desktopPane.add(prs);
            prs.setVisible(true);
            prs.toFront();
        }

    }//GEN-LAST:event_copyMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem affectationProjetMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem enseignantMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem projetRechercheMenuItem;
    // End of variables declaration//GEN-END:variables

}
