/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.ProjetRecherche;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.ProjetRechercheService;

/**
 *
 * @author FATI
 */
public class ProjetByTitreForm extends javax.swing.JInternalFrame {

    private ProjetRechercheService prs;
    private DefaultTableModel model;
    private static ProjetByTitreForm instance;

    /**
     * Creates new form ProjetByTitreForm
     */
    private ProjetByTitreForm() {

        super("Filtrage des projets selon les axes de recherche", true, true, true, true);
        setSize(900, 800);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        initComponents();
        prs = new ProjetRechercheService();
        model = (DefaultTableModel) listProjetsByTitle.getModel();

        loadProjetRecherche();
    }

    public static ProjetByTitreForm getInstance() {
        if (instance == null || instance.isClosed()) {
            synchronized (ProjetByTitreForm.class) { // Synchronisez pour la sécurité des threads
                if (instance == null || instance.isClosed()) {
                    instance = new ProjetByTitreForm();
                }
            }
        }
        return instance;
    }

    private void loadProjetRecherche() {
        model.setRowCount(0);
        for (ProjetRecherche p : prs.findAll()) {
            model.addRow(new Object[]{p.getId(), p.getTitre(), p.getAxe(), p.getDateDebut(), p.getDateFin()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTitre = new javax.swing.JTextField();
        txtChercher = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProjetsByTitle = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(253, 253, 228));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ProjetByTitre"));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\go\\Documents\\NetBeansProjects\\ProjetsDeRecherche\\src\\Images\\icons8-titre-24.png")); // NOI18N
        jLabel1.setText("Titre:");

        txtChercher.setBackground(new java.awt.Color(0, 0, 255));
        txtChercher.setIcon(new javax.swing.ImageIcon("C:\\Users\\go\\Documents\\NetBeansProjects\\ProjetsDeRecherche\\src\\Images\\icons8-chercher-24.png")); // NOI18N
        txtChercher.setText("Rechercher");
        txtChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChercherActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Rechercher un projet par titre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtChercher))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel2)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChercher))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        listProjetsByTitle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titre", "Axe", "Date de début", "Date fin"
            }
        ));
        jScrollPane1.setViewportView(listProjetsByTitle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChercherActionPerformed
        // TODO add your handling code here:

        String titre = txtTitre.getText().trim();

        if (!titre.isEmpty()) {
            model.setRowCount(0);

            ProjetRecherche projet = prs.findByTire(titre);

            if (projet != null) {
                model.addRow(new Object[]{projet.getId(), projet.getTitre(), projet.getAxe(), projet.getDateDebut(), projet.getDateFin()});
            } else {
                JOptionPane.showMessageDialog(this, "Aucun projet trouvé avec ce titre !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez entrer un titre !");
        }

    }//GEN-LAST:event_txtChercherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listProjetsByTitle;
    private javax.swing.JButton txtChercher;
    private javax.swing.JTextField txtTitre;
    // End of variables declaration//GEN-END:variables
}
